---
- name: Generate locales
  locale_gen:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - de_AT.UTF-8
    - de_DE.UTF-8
    - en_GB.UTF-8
    - en_US.UTF-8

- name: Set default locale
  lineinfile:
    path: /etc/default/locale
    regexp: '^LANG='
    line: 'LANG=de_AT.UTF-8'
  become: yes

- name: Set timezone to Europe/Vienna
  timezone:
    name: Europe/Vienna
  become: yes

- name: Default-Services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  become: yes
  with_items:
    - ssh

- name: Install Kernel-modules
  modprobe:
    name: 8021q
    state: present
  become: yes
  when:
    - kernel.kernel_modules
  